config/routes.rb
Oars::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get  '/offered_courses/search', :to => 'offered_courses#search'

  get  '/faculties/course_description', :to => 'faculty#course_description'
  get  '/courses/search', :to => 'courses#search'
  resources :courses
  resources :offered_courses
  resources :course_requests

 
  
  devise_for :faculties,
             :controllers => { :registrations => "faculty/registrations",
                             :sessions => "faculty/sessions" 
                             } do 
        get '/faculties/sign_up', :to => 'faculty/registrations#new', :as => :faculty_sign_up
        get '/faculties/sign_in', :to => 'faculty/sessions#new', :as => :faculty_sign_in
        get '/faculties/sign_out', :to => 'faculty/sessions#destroy', :as => :faculty_sign_out
        get '/faculties/instructor_home', :to => 'faculty#instructor_home', :as => :instructor_home
        get '/faculties/welcome_instructor', :to => 'faculty#welcome_instructor', :as => :welc_instructor
        get '/faculties/personal_info', :to => 'faculty#personal_info' , :as => :faculty_personal_info
        get '/faculties/account', :to => 'faculty#account' , :as => :faculty_account
        get '/faculties/current_sem', :to => 'faculty#current_sem#' , :as => :current_registration
        get '/faculties/Pre_registration', :to => 'faculty#pre_registration' , :as => :faculty_pre_registration
        get '/faculties/courses_taken', :to => 'faculty#courses_taken' , :as => :faculty_courses_taken
        get '/faculties/course_description', :to => 'faculty#course_description' , :as => :faculty_course_description
        get '/faculties/course_requests', :to => 'faculty#course_requests' , :as => :course_list
        get '/faculties/course_info', :to => 'faculty#course_info' , :as => :course_info
        get '/faculties/update_description', :to => 'faculty#update_description' , :as => :update_description
        get '/faculties/accepted', :to => 'faculty#accepted' , :as => :accepted
        get '/faculties/rejected', :to => 'faculty#rejected' , :as => :rejected
        get '/faculties/registration_forms', :to => 'faculty/pre_registration#registration_forms' , :as => :registration_forms
        get '/faculties/approve_form', :to => 'faculty/pre_registration#approve_form' , :as => :approve_form
       
  end 

  get 'students/messages', :to => 'student#view_messages', :as => :student_messages
  get 'faculties/send_message', :to => 'faculty#send_message'

  

  post '/offered_courses/add', :to => 'offered_courses#add'
  post '/students/pre_registration/add', :to => 'student/pre_registration#add'

  post '/offered_courses/delete', :to => 'offered_courses#delete'
  post '/students/pre_registration/delete', :to => 'student/pre_registration#delete'

  post '/students/pre_registration/submit', :to => 'student/pre_registration#submit'
  post '/students/pre_registration/withdraw', :to => 'student/pre_registration#withdraw'
  
  get '/faculties/pre_registration/reject', :to => 'faculty/pre_registration#reject'
  get '/faculties/pre_registration/accept', :to => 'faculty/pre_registration#accept'  
  
  get '/courses/get_constraints', :to => 'courses#get_constraints' , :as => :get_constraints
  get '/courses/view_courses_constraint',:to => 'courses#view_courses_constraint', :as => :view_courses_constraint
  get 'courses/view_templates', :to => 'courses#view_templates', :as => :view_templates
  get 'courses/apply_template', :to => 'courses#apply_template', :as => :apply_template
  get 'courses/modify_template', :to => 'courses#modify_template', :as => :modify_template
  get 'courses/add_template', :to => 'courses#add_template', :as => :add_template
  get 'courses/add_constraint', :to => 'courses#add_constraint', :as => :add_constraint
  get 'courses/modify_constraint', :to => 'courses#modify_constraint', :as => :modify_constraint
  get 'courses/delete_constraint', :to => 'courses#delete_constraint', :as => :delete_constraint
  devise_for :students,
             :controllers => { :registrations => "student/registrations",
                             :sessions => "student/sessions"
                             } do 
        get '/students/sign_up', :to => 'student/registrations#new', :as => :student_sign_up
        get '/students/sign_in', :to => 'student/sessions#new', :as => :student_sign_in
        get '/students/sign_out', :to => 'student/sessions#destroy', :as => :student_sign_out
        get '/students/student_home', :to => 'student#student_home', :as => :student_home
        get '/students/welcome_student', :to => 'student#welcome_student', :as => :welc_student
        get '/students/personal_info', :to => 'student#personal_info', :as => :student_personal_info
        get '/students/current_registration', :to => 'student/current_registration#current_registration', :as => :student_current_registration
        get '/students/pre_registration', :to => 'student/pre_registration#index', :as => :student_pre_registration
        get '/students/add_drop', :to => 'student#add_drop', :as => :student_add_drop
        get '/students/transcript', :to => 'student#transcript', :as => :student_transcript
        get '/students/time_table', :to => 'student#time_table', :as => :student_time_table
        get '/students/backlog_list', :to => 'student#backlog_list', :as => :student_backlog_list
      	
  end

  root :to => "profile#login"

  get 'profile/login'
  get 'profile/contact', :to => 'profile#contact', :as => :contact
  

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                     :integer          not null, primary key
#  roll                   :string(255)
#  username               :string(255)
#  name                   :string(255)
#  phone                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  department_id          :integer
#  template_course_id     :integer
#

class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :department_id
  attr_accessible :name, :phone, :roll, :username
  belongs_to :department
  belongs_to :template_course
  has_many :registration_forms, :dependent => :destroy
  has_many :course_requests
  has_one :academic_information
end

app/controllers/student/current_registration_controller.rb
class Student::CurrentRegistrationController < ApplicationController
  
  def current_registration
  #student_id = params[:q]
  @currentRegistration=RegistrationForm.find(:all,:conditions =>["form_type==? and student_id==?","pre",current_student.id])[0]
  #@courses=@currentRegistration.offered_courses
  end
end 

app/controllers/student/pre_registration_controller.rb
class Student::PreRegistrationController < ApplicationController
  helper Student::PreRegistrationHelper
  def index
    @preform = RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id, 'pre')
    @prereg_courses = @preform.offered_courses
    @is_submitted = @preform.is_submitted
    @is_accepted = @preform.is_accepted
  end

  def add
    @preform = RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id, 'pre')
    id = params[:id]
    @offeredCourse = OfferedCourse.find(params[:id])
    cl = view_context.clash(@offeredCourse,@preform)
    if cl.nil?
        cr = CourseRequest.find_by_student_id_and_offered_course_id(current_student.id, id)
        cr.status = "added"
        cr.save!
        @preform.offered_courses << @offeredCourse
        @preform.save!
        flash[:success] = "Hurray, added to Pre-Registration Form!"
    else 
        flash[:failure] = "Timetable clash with #{cl.course.name}"
    end 
    session[:return_to] = request.referer
    redirect_to session[:return_to]
  end
  def delete
    @preform = RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id, 'pre')
    id = params[:id]
    cr = CourseRequest.find_by_student_id_and_offered_course_id(current_student.id, id)
    cr.status = "accepted"
    cr.save!
    @offeredCourse = OfferedCourse.find(params[:id])
    @preform.offered_courses.delete(@offeredCourse)
    @preform.save!
    flash[:success] = "Hurray, added to Pre-Registration Form!"
    session[:return_to] = request.referer
    redirect_to session[:return_to]
  end

  def submit
    @preform = RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id, 'pre')
    @preform.is_submitted = true
    @preform.save!
    flash[:success] = "Hurray, submitted you Pre-Registration Form to DUGC for approval!"
    session[:return_to] = request.referer
    redirect_to session[:return_to]
  end

  def withdraw
    @preform = RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id, 'pre')
    @preform.is_submitted = false
    @preform.save!
    flash[:success] = "Withdrew your Pre-Registration Form from DUGC :("
    session[:return_to] = request.referer
    redirect_to session[:return_to]
  end
end

app/controllers/student/registrations_controller.rb
# app/controllers/student/registrations_controller.rb
class Student::RegistrationsController < Devise::RegistrationsController
  
  def new
    super
  end

  def create
    # add custom create logic here
    super
  end

  def update
    super
  end

  def after_sign_up_path_for(resource)
    welc_student_path
  end

  def after_update_path_for(resource)
    student_personal_info_path
  end
end

app/controllers/student/sessions_controller.rb
# app/controllers/student/sessions_controller.rb
class Student::SessionsController < Devise::SessionsController
  before_filter :faculty_out

  def new
    super
  end

  def create
    # add custom create logic here
    super
  end

  def destroy
    super
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || student_personal_info_path
  end
  
end

def faculty_out
    if faculty_signed_in?
        reset_session
    end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
        before_filter :authenticate_student! 
        include StudentHelper
        def welcome_student
        end
        
        def student_home
        end

        def personal_info
        end
        
        def current_registration
        end
        
        def backlog_list
        end

        def view_messages
          alfa = Student.find(current_student.id)
          #alfa gets the last conversation (chronologically, the first in the inbox)
          @conversations = alfa.mailbox.inbox
          #@receipts = @conversations.map { |c| c.receipts_for alfa }.flatten
          #alfa gets it receipts chronologically ordered.
          #@receipts = @conversation.receipts_for alfa

        end
         
        def transcript
          @ai = AcademicInformation.find_or_create_by_student_id(current_student.id)
          @ss = CourseTaken.where(:academic_information_id => @ai.id).group("semester").count
          @semesters = []
          @ss.keys.each do |no|
              semester = Hash.new
              semester[:number] = no 
              semester[:cpi] = "%0.2f" % calc_cpi(no,current_student)
              semester[:spi] = "%0.2f" % calc_spi(no,current_student)
              semester[:courses] = CourseTaken.where(:academic_information_id => @ai.id, :semester => no)
              @semesters << semester
          end 
        end
        
        def add_drop
        end

        def time_table 
            @start_date = Date.new(2000,1,3)
            @end_date = Date.new(2000,1,7)
            @date = Date.new(2000,1,3)
            @events  = RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id, 'pre').offered_courses.map{|c| c.lecture_times}.flatten 
        end 
end

app/helpers/student/pre_registration_helper.rb
module Student::PreRegistrationHelper
    def clash(course_to_add,form)
        form.offered_courses.each do |r|
            r.lecture_times.each do |l|
                course_to_add.lecture_times.each do |c|
                    if l.day == c.day
                        if l.starts_at >= c.starts_at and l.starts_at < c.ends_at 
                            return r 
                        elsif c.starts_at >= l.starts_at and c.starts_at < l.ends_at 
                            return r
                        end 
                    end 
                end
            end
        end
        return nil 
    end 
    def is_submitted?
      RegistrationForm.find_or_create_by_student_id_and_form_type(current_student.id,'pre').is_submitted
    end
end

app/helpers/student_helper.rb
module StudentHelper 
    def calc_cpi(semester,student)
        total_credits = 0 
        total = 0 
        "1".upto(semester).each do |s|
            credits = calc_credits(s,student)
            total = total + (calc_spi(s,student) * credits)
            total_credits = total_credits + credits 
        end 
        return total/total_credits.to_f

    end 
    def calc_spi(semester,student)
          ai = AcademicInformation.find_or_create_by_student_id(student.id)
          total = ai.course_takens.select{|s| s.semester ==  semester}.map{|s| s.credits * convert_grade(s.grade)}.sum
          credits = calc_credits(semester,student)
          return total/credits.to_f
    end 
    def calc_credits(semester,student)
          ai = AcademicInformation.find_or_create_by_student_id(student.id)
          ai.course_takens.select{|s| s.semester == semester}.map{|s| s.credits}.sum
    end 
    def convert_grade(grade)
        h = Hash.new()
        h["A"] = 10
        h["B"] = 8 
        h["C"] = 6
        h["D"] = 4 
        h["F"] = 2
        return h[grade]
    end 
end 

app/views/student/add_drop.html.erb
<div class="center hero-unit">
        <h3>Add-Drop</h3>
        <h5>Please Drop a Course before you Add one. You can add courses from Offered Courses page!</h5>
        
        <p>
        <div align="center">
<!--                 <SPAN style="BACKGROUND-COLOR: #aaffbb">List of Currently Registered Courses</SPAN> -->
                <p class="text-warning" style="color:#eecc00"><em>List of Currently Registered Courses</em></p>
        </div>
        <table class="center table">
                <tr class="info"><td>Course</td><td>Title</td><td>Units</td><td>Section</td><td>R/S</td><td>R/S Course </td><td></td></tr>
                
                <tr><td>cs455</td><td>Introduction to software engineering</td><td>4</td><td>-</td><td>-</td><td>-</td><td><button class="btn btn-small btn-danger"><%= link_to "Drop", "#" %></button></td></tr>
        </table>
        
        
        <div align="center">
                <p class="text-warning" style="color:#eecc00"><em>List of Requested Courses</em></p>
        </div>
        <table class="center table">
                <tr class="info"><td>Course</td><td>Title</td><td>Units</td><td>Status</td><td>Course-Type</td><td></td></tr>

                <tr><td>cs455</td><td>Introduction to Software Engineering</td><td>4</td><td>Waiting</td><td>Compulsory</td><td><button class="btn btn-small btn-danger"><%= link_to "Delete", "#" %></button></td></tr>
                <tr><td>cs455</td><td>Applied Stochastic</td><td>4</td><td>Rejected</td><td>SE</td><td><button class="btn btn-small btn-danger" disabled="disabled">Delete</button></td></tr>
                <!--<tr><td>cs455</td><td>Artificial Intelligence</td><td>4</td><td>Accepted</td><td>SE</td><td><button class="btn btn-small btn-danger"><%= link_to "Delete", "#" %></button></td></tr>-->
        </table>
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/student/backlog_list.html.erb
<div class="center hero-unit">
        <div class="btn-toolbar">        
        <div class="center btn-group">
                <button class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown">Academic Information
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                        <li><%= link_to "Transcript", student_transcript_path   %></li>
                        <li><%= link_to "Backlog List", student_backlog_list_path   %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Student Information", student_personal_info_path   %></li>
                </ul>
        </div>
    </div>
        
        <h4>List of Backlogs</h4>
        
        <p>
                <table class="center table">
			<tr class="info"><td>Course</td><td>Title</td><td>Units</td></tr>
       
    <% current_student.academic_information.course_takens.each do |ct| %>
        <% if ct.grade == "F" %>      
            <tr><td><%= ct.course.number %></td><td><%= ct.course.name %></td><td><%= ct.credits %></td></tr>
        <% end %> 
    <% end %> 
        </table>
        </p>
        
        
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/student/current_registration.html.erb
<div class="center hero-unit">
        <h3>Current-Semester</h3>
        <h5>Here is your current Semester!</h5>

        <p>
        <div align="right" class="btn-group">
                <%= link_to "Pre Registration", student_pre_registration_path, class: "btn btn-large btn-success"  %>
        </div>
        <table class="center table">
                <tr class="info"><td>Course</td><td>Title</td><td>Units</td><td>Section</td><td>R/S</td><td>R/S Course </td></tr>

                <!--<% @currentRegistration %> -->     
                <tr><td>cs455</td><td>Introduction to software engineering</td><td>4</td><td>-</td><td>-</td><td>-</td></tr>
                <tr><td><%=@currentRegistration.form_type%></td><td><%=%></td><td><%=%></td><td><%=%>-</td><td><%=%>-</td><td><%=%>-</td></tr>
              <!--   <% %> -->
        </table>
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/student/personal_info.html.erb
<div class="hero-unit">
    <h3 align="center">Always keep your Personal Information Updated! :)</h3>
            <div class="center btn-toolbar">
            <div class="center btn-group">
                <button class="btn btn-large btn-primary dropdown-toggle" align="left" data-toggle="dropdown">Academic Information
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                        <li><%= link_to "Transcript", student_transcript_path   %></li>
                        <li><%= link_to "Backlog List", student_backlog_list_path   %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Student Information", student_personal_info_path   %></li>
                </ul>
            </div>
            </div>

        <p>
        <table class="table">
            <tr><td width="200">Roll Number :</td><td width="300"><%= current_student.roll %></td></tr>
                <tr><td>Name :</td><td><%= current_student.name %></td></tr>
                <tr><td>Email :</td><td><%= current_student.email %></td></tr>
                <tr><td>Telephone :</td><td><%= current_student.phone %></td></tr>
        </table>
        </p>
        
        <p align="left">
                <%= link_to "Update Info", edit_student_registration_path, class: "btn btn-link btn-large btn-danger" %>
        </p>
        
</div>

app/views/student/pre_registration.html.erb
<div class="center hero-unit">
        <h3>Pre-Registration</h3>
        <h5>Courses you have Requested!</h5>
        <h6>To request any course proceed to the course list!</h6>

        <p>
        <div align="right" class="btn-group">
                <%= link_to "Current Registration", student_current_registration_path, class: "btn btn-large btn-success" %>
        </div>
        <table class="center table">
                <tr class="info"><td>Course</td><td>Title</td><td>Units</td><td>Status</td><td>Course-Type</td><td></td></tr>
				<% @waiting_courses.each do |course| %>
                <tr><td><%=course.course.number%></td><td><%=course.course.name%></td><td><%=course.credit%></td><td>Waiting</td><td>notdefined</td><td><%= link_to "Delete", "#", class: "btn btn-small btn-danger" %></td></tr>
                <% end %>
                <% @accepted_courses.each do |course| %>
                <tr ><td><%=course.course.number%></td><td><%=course.course.name%></td><td><%=course.credit%></td><td>Accepted</td><td>SE</td><td><button class="btn btn-small btn-danger" disabled="disabled">Delete</button></td></tr>
                <%end%>
                
        </table>
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/student/student_home.html.erb
<div class="center hero-unit">
  <h3>Hello 'Name'! Your Personal Info.</h3>

  <h4>
    <!--<%= link_to "You are a Student!", 'welc_student', class: "btn btn-large btn-primary" %> <%= link_to "You are an Instructor!", 'welc_instructor', class: "btn btn-large btn-primary" %>-->
  </h4>

  <h5>
<!--     Please select the respective links. -->
  </h5>
</div>
        

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/student/time_table.html.erb
<% weekly_calendar(@events, :date => @date, :include_24_hours => true) do |w| %> 
  <% w.week(:business_hours => params[:business_hours]) do |event,truncate| %> 
      <%= event.starts_at.strftime('%I:%M%p') %> </br>
      <%= link_to event.offered_course.course.number, offered_course_path(event.offered_course.id), :remote => true %>
  <% end -%> 
<% end -%>

app/views/student/transcript.html.erb
<div class="hero-unit">
            <div class="center btn-toolbar">
        <div class="btn-group">
                <button class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown">Academic Information
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                        <li><%= link_to "Transcript", student_transcript_path   %></li>
                        <li><%= link_to "Backlog List", student_backlog_list_path   %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Student Information", student_personal_info_path   %></li>
                </ul>
        </div>
    </div>
        
        <h4 align="center">Your Transcript</h4>
        <!-- set the column width as per convinence -->
        <p>
        <table class="center table table-striped">
        <col width="60"><col width="80"><col width="5"><col width="5">
        <tr class="info"><td>Course</td><td>  Title </td><td>Units</td><td>Grade</td></tr>
        </table>
        <!-- loops over number of Semester <% %> -->
        <% @semesters.each do |sem| %>
            <p align="center">Semester <%=sem[:number]%></p> </br> <p align="right"> CPI = <%=sem[:cpi]%> SPI = <%= sem[:spi] %></p>
        <table class="center table">
        <col width="20"><col width="60"><col width="5"><col width="5">
                <!-- loop over courses <%  %> -->
                <% sem[:courses].each do |course| %>
                <tr>
                  <td><%= course.course.number %></td>
                  <td><%= course.course.name %></td>
                  <td><%= course.credits %></td>
                  <td><%= course.grade %></td>
                </tr>
                <!--end loop <% %> -->
                <% end %>
        </table>
        <% end %>
        </p>
</div>

app/views/student/view_messages.html.erb
<div id="messages">
<h2> Messages </h2>
<div class="accordion" id="accordion2">
  
  <% @conversations.each do |c| 
       receipts = c.receipts
       receipts.each do |receipt|
        message = receipt.message %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">      
        <p> Message from  <%=   c.originator.name %>, <%= c.originator.email %> </p>
      </a>
    </div>
  <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
        <div class="well well-large">
        <p> Subject : <%=   message.subject %> </p> 
        <p> <%=   message.body  %> 
        </div>
      </div>
    </div>
  </div>
    
    <% end %>
  <% end %>

app/views/student/welcome_student.html.erb
<div class="center hero-unit">
  <h3>Hello Student! Proceed to Login if you have an account here already or Sign Up otherwise.</h3>

  <h4>
    <!--<%= link_to "You are a Student!", 'welc_student', class: "btn btn-large btn-primary" %> <%= link_to "You are an Instructor!", 'welc_instructor', class: "btn btn-large btn-primary" %>-->
  </h4>

  <h5>
<!--     Please select the respective links. -->
  </h5>
</div>
        

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>