config/routes.rb
Oars::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get  '/offered_courses/search', :to => 'offered_courses#search'

  get  '/faculties/course_description', :to => 'faculty#course_description'
  get  '/courses/search', :to => 'courses#search'
  resources :courses
  resources :offered_courses
  resources :course_requests

 
  
  devise_for :faculties,
             :controllers => { :registrations => "faculty/registrations",
                             :sessions => "faculty/sessions" 
                             } do 
        get '/faculties/sign_up', :to => 'faculty/registrations#new', :as => :faculty_sign_up
        get '/faculties/sign_in', :to => 'faculty/sessions#new', :as => :faculty_sign_in
        get '/faculties/sign_out', :to => 'faculty/sessions#destroy', :as => :faculty_sign_out
        get '/faculties/instructor_home', :to => 'faculty#instructor_home', :as => :instructor_home
        get '/faculties/welcome_instructor', :to => 'faculty#welcome_instructor', :as => :welc_instructor
        get '/faculties/personal_info', :to => 'faculty#personal_info' , :as => :faculty_personal_info
        get '/faculties/account', :to => 'faculty#account' , :as => :faculty_account
        get '/faculties/current_sem', :to => 'faculty#current_sem#' , :as => :current_registration
        get '/faculties/Pre_registration', :to => 'faculty#pre_registration' , :as => :faculty_pre_registration
        get '/faculties/courses_taken', :to => 'faculty#courses_taken' , :as => :faculty_courses_taken
        get '/faculties/course_description', :to => 'faculty#course_description' , :as => :faculty_course_description
        get '/faculties/course_requests', :to => 'faculty#course_requests' , :as => :course_list
        get '/faculties/course_info', :to => 'faculty#course_info' , :as => :course_info
        get '/faculties/update_description', :to => 'faculty#update_description' , :as => :update_description
        get '/faculties/accepted', :to => 'faculty#accepted' , :as => :accepted
        get '/faculties/rejected', :to => 'faculty#rejected' , :as => :rejected
        get '/faculties/registration_forms', :to => 'faculty/pre_registration#registration_forms' , :as => :registration_forms
        get '/faculties/approve_form', :to => 'faculty/pre_registration#approve_form' , :as => :approve_form
       
  end 

  get 'students/messages', :to => 'student#view_messages', :as => :student_messages
  get 'faculties/send_message', :to => 'faculty#send_message'

  

  post '/offered_courses/add', :to => 'offered_courses#add'
  post '/students/pre_registration/add', :to => 'student/pre_registration#add'

  post '/offered_courses/delete', :to => 'offered_courses#delete'
  post '/students/pre_registration/delete', :to => 'student/pre_registration#delete'

  post '/students/pre_registration/submit', :to => 'student/pre_registration#submit'
  post '/students/pre_registration/withdraw', :to => 'student/pre_registration#withdraw'
  
  get '/faculties/pre_registration/reject', :to => 'faculty/pre_registration#reject'
  get '/faculties/pre_registration/accept', :to => 'faculty/pre_registration#accept'  
  
  get '/courses/get_constraints', :to => 'courses#get_constraints' , :as => :get_constraints
  get '/courses/view_courses_constraint',:to => 'courses#view_courses_constraint', :as => :view_courses_constraint
  get 'courses/view_templates', :to => 'courses#view_templates', :as => :view_templates
  get 'courses/apply_template', :to => 'courses#apply_template', :as => :apply_template
  get 'courses/modify_template', :to => 'courses#modify_template', :as => :modify_template
  get 'courses/add_template', :to => 'courses#add_template', :as => :add_template
  get 'courses/add_constraint', :to => 'courses#add_constraint', :as => :add_constraint
  get 'courses/modify_constraint', :to => 'courses#modify_constraint', :as => :modify_constraint
  get 'courses/delete_constraint', :to => 'courses#delete_constraint', :as => :delete_constraint
  devise_for :students,
             :controllers => { :registrations => "student/registrations",
                             :sessions => "student/sessions"
                             } do 
        get '/students/sign_up', :to => 'student/registrations#new', :as => :student_sign_up
        get '/students/sign_in', :to => 'student/sessions#new', :as => :student_sign_in
        get '/students/sign_out', :to => 'student/sessions#destroy', :as => :student_sign_out
        get '/students/student_home', :to => 'student#student_home', :as => :student_home
        get '/students/welcome_student', :to => 'student#welcome_student', :as => :welc_student
        get '/students/personal_info', :to => 'student#personal_info', :as => :student_personal_info
        get '/students/current_registration', :to => 'student/current_registration#current_registration', :as => :student_current_registration
        get '/students/pre_registration', :to => 'student/pre_registration#index', :as => :student_pre_registration
        get '/students/add_drop', :to => 'student#add_drop', :as => :student_add_drop
        get '/students/transcript', :to => 'student#transcript', :as => :student_transcript
        get '/students/time_table', :to => 'student#time_table', :as => :student_time_table
        get '/students/backlog_list', :to => 'student#backlog_list', :as => :student_backlog_list
      	
  end

  root :to => "profile#login"

  get 'profile/login'
  get 'profile/contact', :to => 'profile#contact', :as => :contact
  

end

app/models/faculty.rb
# == Schema Information
#
# Table name: faculties
#
#  id                     :integer          not null, primary key
#  pfno                   :string(255)
#  username               :string(255)
#  name                   :string(255)
#  phone                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  department_id          :integer
#

class Faculty < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :pfno, :phone, :username, :department_id
  has_and_belongs_to_many :offered_courses
  belongs_to :department
end

app/controllers/faculty/pre_registration_controller.rb
class Faculty::PreRegistrationController < ApplicationController
 
  def registration_forms
			if !(current_faculty.department.dugc.faculty==current_faculty)
				flash[:error]="#{current_faculty.name}!! you are not authorized for this action"
				redirect_to :action=>'instructor_home'
				end 
			@registration_forms=[]
			current_faculty.department.students.each do |student|
				 student.registration_forms.each do |regform|
				 	if regform.form_type=="pre" and regform.is_submitted==true and regform.is_accepted.nil?
					 	@registration_forms << regform
				 		end
				 	end
				end
		end		
 	def approve_form
			if !(current_faculty.department.dugc.faculty==current_faculty)
				flash[:error]="#{current_faculty.name}!! you are not authorized for this action"
				redirect_to :action=>'instructor_home'
				end 
			@pregform=RegistrationForm.find(params[:regform_id])
	end
  def accept
    @pregform = RegistrationForm.find(params[:pregform_id])
    @pregform.is_accepted=true
    @pregform.save!
    flash[:success] = "Accepted pre-registration form for #{@pregform.student.name}"
   
    redirect_to :action => "registration_forms",:controller=> "faculty/pre_registration"
  end
  
  def reject
    @pregform = RegistrationForm.find(params[:pregform_id])
    @pregform.is_accepted=false
    @pregform.save!
    flash[:danger] = "Rejected pre-registration form for #{@pregform.student.name}"
   
    redirect_to :action => "registration_forms",:controller=> "faculty/pre_registration"
  end

end

app/controllers/faculty/registrations_controller.rb
# app/controllers/faculty/registrations_controller.rb
class Faculty::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    # add custom create logic here
    super
  end

  def update
    super
  end

  def after_sign_up_path_for(resource)
    welc_instructor_path
  end

  def after_update_path_for(resource)
    instructor_personal_info_path
  end


end

app/controllers/faculty/sessions_controller.rb
# app/controllers/faculty/sessions_controller.rb
class Faculty::SessionsController < Devise::SessionsController
  before_filter :student_out
  def new
    super
  end

  def create
    # add custom create logic here
    super
  end

  def destroy
    super
  end


  def after_sign_in_path_for(resource)
    stored_location_for(resource) || faculty_personal_info_path
  end


end

def student_out
    if student_signed_in?
        reset_session
    end
end

app/controllers/faculty_controller.rb
class FacultyController < ApplicationController
before_filter :authenticate_faculty!        
        def instructor_home
        end
        
        def welcome_instructor
        end
        
        def faculty_personal_info
        end
        
        def pre_registration
        end
		
        def account
        end
		
		
		
        def accepted

                request=CourseRequest.find(params[:request_id])
                student=request.student
                request.status="accepted"			
                request.save
                flash[:success] = " #{student.name} is successfully pre-registered"
                redirect_to :action => 'course_requests',:id=>params[:course_id] 
        end
		
        def rejected
                request=CourseRequest.find(params[:request_id])
                student=request.student
                request.status="rejected"			
                request.save
                flash[:alert] = " #{student.name} request is rejected"
                redirect_to :action => 'course_requests',:id=>params[:course_id] 
        end
        
        def courses_taken
        	@courses_taken=OfferedCourse.find(:all)
        	@courses_taken.each do |course|
        		if !course.faculties.include? current_faculty
        			@courses_taken=@courses_taken-[course]
        		end
        	end
        end
        
        def update_description
                #@course_described = OfferedCourse.find(params[:id])
                
                desc = params[:q]
                
                courseDesMod = OfferedCourse.find(params[:name])
                courseDesMod.description = desc
                flash[:success] = "Course Description Updated."
                session[:return_to] = request.referer
                redirect_to session[:return_to]
        end
        def course_description
                @course_described = OfferedCourse.find(params[:id])
        end
        
        def course_info
                @present_course = OfferedCourse.find(params[:id]).course
                @past_current_student_list = CourseTaken.where(:course_id => @present_course.id).map{|p| p.student}
        end

        def send_message
          s = Student.find(params[:student_id])
          f = Faculty.find(current_faculty.id)
          f.send_message(s, "Addition details required", "Meet")
          flash[:success] = "Sent a Meet message to the student!!"
          
          session[:return_to] = request.referer
          redirect_to session[:return_to]
        end

        def course_requests
        @request_list=[]        
        @offered_course=OfferedCourse.find(params[:id])
        request_set=@offered_course.course_requests
        	request_set.each do |request|
        		if request.status=="add"
               		@request_list << request
               		end
            end
        end
        
        def current_sem
          
        end
        
        
end

app/views/faculty/account.html.erb
<div class="center hero-unit">
        <h3>Account</h3>

<% if current_faculty==current_faculty.department.dugc.faculty %>
You are dugc <br>
<%= link_to "Approve Student Forms", registration_forms_path, class: "btn btn-large btn-success"%><br>To modify/introduce constraints<br>
<%= link_to "Course Constraints", view_templates_path, class: "btn btn-large btn-primary"%> 
<% else %>
 you are only a faculty
 <%end%>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>        

app/views/faculty/approve_form.html.erb
<div class="center hero-unit">
        <h3>Pre-registration Form</h3>
        <h5><%=@pregform.student.name%> (<%=@pregform.student.roll%>)</h5>
        <h6>DUGC Approval</h6>

        <p>
        
        <table class="center table">
                <tr class="info"><td>Course</td><td>Title</td><td>Units</td></tr>
			
                <% @pregform.offered_courses.each do |course| %>
                <tr>
                  <td><%=course.course.number%></td>
                  <td><%=course.course.name%></td>
                  <td><%=course.credit%></td>
                </tr>
                <%end%>
                </table>
                <%= link_to "Accept", {:action => "accept",
            :controller=> "faculty/pre_registration", :pregform_id => @pregform.id } , {:class =>
            "btn btn-small btn-success"} 
            %>
            <%= link_to "Reject", {:action => "reject",
            :controller=> "faculty/pre_registration", :pregform_id => @pregform.id } , {:class =>
            "btn btn-small btn-danger"}%> 
            
        
      </p>  
</div>

app/views/faculty/course_description.html.erb
<h2 align="center">Description for <%= @course_described.course.number %> <%= @course_described.course.name %></h2>

<%= form_tag("/faculties/update_description", :method => "get"  ) do %>
  <%= label_tag(:q, "Course Description:") %>
  <%= text_area_tag(:q) %>
  
  <%= hidden_field_tag(:name, @course_described.id) %>
  </br>
  <%= submit_tag("Update") %>
<% end %>

<%= link_to "Back", :back %>

app/views/faculty/course_info.html.erb
<div class="center hero-unit">
                
        <h3>Registered Students in <%=@present_course.number%> </h3>
        <p>        
        <%if !@past_current_student_list.empty? %>
                <table class="center table">
                        <tr class="info"><td>Student Name</td><td>Roll Number</td><td>Info</td></tr>
                        <% @past_current_student_list.each do |student| %>      
                        <tr><td><%=student.name%></td><td><%=student.roll%></td><td>Good Boy</td></tr>
                        <%end %>
                </table>
        <%else%>
                No students Registered.
        <%end%> 
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/course_requests.html.erb
<div class="center hero-unit">
		
		<h3>Student requested for Course <%=@offered_course.course.number%> </h3>
		
        <table class="center table">
			<tr class="info"><td>Student Name</td><td>Roll Number</td><td>Info</td><td>Accept</td><td>Reject</td><td>Meet</td></tr>
       	 <% @request_list.each do |request| %>      
   			<tr><td><%=request.student.name%></td><td><%=request.student.roll%></td><td>Backchod
   			hai</td><td><%=link_to "Accept", {:action =>
   			"accepted", :course_id => @offered_course.id,
   			:request_id=>request.id},{:class =>"btn
   			btn-mini btn-primary"}
   			%></td><td><%=link_to "Reject", {:action =>
   			"rejected", :course_id => @offered_course.id,
   			:request_id=>request.id},{:class =>"btn
   			btn-mini btn-danger"} %></td>
                        <td>
                          <%=link_to "Meet", {:action =>
                          "send_message", :student_id =>
                          request.student.id }, {:class => "btn
                          btn-mini btn-primary" } %>
                        </td>
                        </tr>
      		 <%end %>
        </table>
        <%if !@request_list.empty? %>
       <%else%>
        No more pending requests.
        <%end%>        
		
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/courses_taken.html.erb
<div class="center hero-unit">
        <%if !@courses_taken.empty?%>
        <h3>Your Courses Next semester </h3>
		<p>
		
        <table class="center table">
        <tr class="info"><td>Course</td><td>Title</td><td>Credit</td><td>Get Student List</td></tr>
                <% @courses_taken.each do |course| %>      
   			<tr><td><%= course.course.number %></td><td><%= link_to course.course.name, { :action => "course_description", :id => course.id} %></td><td><%=course.credit%></td><td><%=link_to "Get Student List",{ :action => "course_requests", :id => course.id}, {:class => "btn btn-mini btn-primary"}%></td></tr>
      		<% end %>
      	</table>
      	</p> 
        <%else%>
      	<p>	Hurray!! you don't have any course this semester<br></p>
      	<%end%>
               
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/current_registration.html.erb
<div class="center hero-unit">
        <%if !@courses_taken.empty?%>
        <h3>Current Semester Info</h3>

        <h5>
                Courses this semester
        </h5>
        <p>
        <table class="center table">
                <tr class="info"><td>Course</td><td>Title</td><td>Credit</td><td>Info</td></tr>
                <% @courses_taken.each do |course| %>      
                        <tr><td><%= course.course.number %></td><td><%=course.course.name%></td><td><%=course.credit%></td><td><%=link_to "Info",{ :action => "course_info", :id => course.id}, {:class => "btn btn-mini btn-primary"}%></td></tr>
                <% end %>
        </table>
        </p> 
        <%else%>
        <p>Hurray!! you don't have any course this semester<br></p>
        <%end%>
               
</div>

app/views/faculty/current_sem.html.erb
<div class="center hero-unit">
        <%if !@courses_taken.empty?%>
        <h3>Your Courses This semester </h3>
		<p>
		
        <table class="center table">
        <tr class="info"><td>Course</td><td>Title</td><td>Credit</td><td>Get Student List</td></tr>
                <% @courses_taken.each do |course| %>      
   			<tr><td><%= link_to course.course.number, course, :remote => true %></td><td><%= link_to course.course.name, course, :remote => true %></td><td><%=course.credit%></td><td><%=link_to "Get Student List",{ :action => "course_requests", :id => course.id}, {:class => "btn btn-mini btn-primary"}%></td></tr>
      		<% end %>
      	</table>
      	</p> 
        <%else%>
      	<p>	Hurray!! you don't have any course this semester<br></p>
      	<%end%>
               
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/instructor_home.html.erb
<div class="center hero-unit">
  <h3>Hello 'Name'! Your Personal Info.</h3>

  <h4>
    <!--<%= link_to "You are a Student!", 'welc_student', class: "btn btn-large btn-primary" %> <%= link_to "You are an Instructor!", 'welc_instructor', class: "btn btn-large btn-primary" %>-->
  </h4>

  <h5>
<!--     Please select the respective links. -->
  </h5>
</div>
        

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/personal_info.html.erb
<div class="center hero-unit">
        <h3>Always keep your Personal Information Updated! :)</h3>
        <p>
        <table class = "center table">
            <tr><td width="200">Pf Number :</td><td width="300"><%= current_faculty.pfno %></td></tr>
                <tr><td>Name :</td><td><%= current_faculty.name %></td></tr>
                <tr><td>Email :</td><td><%= current_faculty.email %></td></tr>
                <tr><td>Telephone :</td><td><%= current_faculty.phone %></td></tr>
        </table>
        </p>
        
        <p>
                <button class="btn btn-link btn-large btn-danger"><%= link_to "Update Info", edit_faculty_registration_path %></button>
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/pre_registration.html.erb
<div class="center hero-unit">
        <h3>Student requested for Courses cs455 </h3>

        <table class="center table">
			<tr class="info"><td>Student Name</td><td>Roll Number</td><td>Info</td><td>Status</td></tr>
       
			<!-- loop over no of students <%  %> -->      
   			<tr><td>Satvik Chuhan</td><td>Y9123</td><td>Cool</td><td><%=link_to "Auto-accepted",'#' ,class: "btn btn-mini btn-primary" %></td></tr>
      		<!-- <% %> -->
        </table>
        </p>
        
</div>



<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>

app/views/faculty/welcome_instructor.html.erb
<div class="center hero-unit">
  <h3>Hello Professor! Proceed to Login if you have an account here already or Sign Up otherwise.</h3>

  <h4>
    <!--<%= link_to "You are a Student!", 'welc_student', class: "btn btn-large btn-primary" %> <%= link_to "You are an Instructor!", 'welc_instructor', class: "btn btn-large btn-primary" %>-->
  </h4>

  <h5>
<!--     Please select the respective links. -->
  </h5>
</div>
        

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://iitk.ac.in/' %>